name: Epilog Build

on:
  push:
    branches: [ master ]
    paths: [ 'env/rebuild-all.txt', 'env/rebuild-windows.txt' ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: download boost
      shell: powershell
      run: |
        $uri = 'https://boostorg.jfrog.io/artifactory/main/release/1.74.0/binaries/boost_1_74_0-msvc-14.2-64.exe'
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $uri -OutFile C:\boost.exe -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
    - name: install boost
      shell: cmd
      run: |
        C: && cd \ && "C:\boost.exe" /sp- /verysilent /suppressmsgboxes /norestart |more
    - name: libsecp
      run: git clone https://github.com/datavetaren/secp256k1-zkp ../secp256k1-zkp
    - name: build
      shell: cmd
      run: make.bat all
    - name: zip
      shell: cmd
      run: |
        cd bin && "C:\Program Files\7-Zip\7z.exe" a -tzip -r epilog_windows_latest.zip epilogd.exe epilog-data
    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/epilog_windows_latest.zip
        asset_name: epilog_windows_latest.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest build of Epilog"
