name: Epilog Build

on:
  push:
    branches: [ master ]
    paths: [ 'env/rebuild-all.txt', 'env/rebuild-linux.txt' ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: sudo apt update
    - name: gdb
      run: sudo apt-get install gdb
    - name: boost
      run: sudo apt-get install libboost-all-dev
    - name: libsecp
      run: git clone https://github.com/datavetaren/secp256k1-zkp ../secp256k1-zkp
    - name: build
      run: make all
    - name: zip
      run: cd bin && zip -r epilog_linux_ubuntu_22_latest.zip epilogd epilog-data
    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/epilog_linux_ubuntu_22_latest.zip
        asset_name: epilog_linux_ubuntu_22_latest.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest build of Epilog"
