name: Epilog Build

on:
  push:
    branches: [ master ]
    paths: [ 'env/rebuild-all.txt', 'env/rebuild-mac.txt' ]
  pull_request:
    branches: [ master ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: brew install boost
    - name: coreutils
      run: brew install coreutils
    - name: libsecp
      run: git clone https://github.com/datavetaren/secp256k1-zkp ../secp256k1-zkp
    - name: build
      run: make all
    - name: zip
      run: cd bin && zip -r epilog_macosx_monterey_latest.zip epilogd epilog-data
    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/epilog_macosx_monterey_latest.zip
        asset_name: epilog_macosx_monterey_latest.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest build of Epilog"
