name: Epilog Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: brew install boost
    - name: libsecp
      run: git clone https://github.com/datavetaren/secp256k1-zkp ../secp256k1-zkp
    - name: build
      run: make all
    - name: zip
      run: cd bin && zip -r epilog_macosx_catalina_latest.zip epilogd epilog-data
    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/epilog_macosx_catalina_latest.zip
        asset_name: epilog_macosx_catalina_latest.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest build of Epilog"
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: sudo apt update
    - name: gdb
      run: sudo apt-get install gdb
    - name: boost
      run: sudo apt-get install libboost-all-dev
    - name: libsecp
      run: git clone https://github.com/datavetaren/secp256k1-zkp ../secp256k1-zkp
    - name: build
      run: make all
    - name: zip
      run: cd bin && zip -r epilog_linux_ubuntu_18_latest.zip epilogd epilog-data
    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/epilog_linux_ubuntu_18_latest.zip
        asset_name: epilog_linux_ubuntu_18_latest.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest build of Epilog"
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: download boost
      shell: powershell
      run: |
        $uri = 'http://www.datavetaren.se/boost/boost_1_71_0_msvc14_2.zip'
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $uri -OutFile C:\boost.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
    - name: install boost
      shell: cmd
      run: |
        C: && cd \ && "C:\Program Files\7-Zip\7z.exe" x -tzip C:\boost.zip
    - name: libsecp
      run: git clone https://github.com/datavetaren/secp256k1-zkp ../secp256k1-zkp
    - name: build
      shell: cmd
      run: make.bat all
    - name: zip
      shell: cmd
      run: |
        cd bin && "C:\Program Files\7-Zip\7z.exe" a -tzip -r epilog_windows_10_latest.zip epilogd.exe epilog-data
    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/epilog_windows_10_latest.zip
        asset_name: epilog_windows_10_latest.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest build of Epilog"
